### ISSUE TITLE
Straight after installing

### ISSUE THREAD

**Issue by AppleTechy** [gw-wiscon/homebridge-onkyo-avr#1]
I tried running the homebridge after installing and when it tried to instalize the plugin I received this error 
"/usr/local/lib/node_modules/homebridge/lib/api.js:47
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'OnkyoAVR' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:47:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:164:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:36:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
"

**Comment by gw-wiscon** [comment]
Are you sure the plugin is installed correctly?
Try to execute the following command:
sudo npm install -g homebridge-onkyo-avr

**Comment by AppleTechy** [comment]
Yes I am positive it was correctly installed. What is on the line that is
saying was incorrect? Did I some how screw up the IP address or something
and that is causing the error? @gw-wiscon

**Comment by gw-wiscon** [comment]
The log states that no plug-in can be found that registers the name "OnkyoAVR".
This is mostly indictating an installation issue.
Can you try to install again, and sent me the log?

**Comment by toshibochan** [comment]
I able to install, but some time crash my server. 
And I can only turn on and off. I can't change inputs?

**Comment by gw-wiscon** [comment]
The crash, I have seen too. Unsure what caused it. Still investigating.

The plugin is very young, I just had time to make it control the power. If you have time to extend it, then please do so.

**Comment by gw-wiscon** [comment]
Can you please update to the latest version, I believe I have resolved the crash issue.

**Comment by AppleTechy** [comment]
Ok I can give it a shot. I ended  up buying a Harmony hub as to not have to worry about plugins for everything but I am more than happy to test the plugin for you some more

**Comment by gw-wiscon** [comment]
Please do.

**Comment by uronito** [comment]
Hi another time jejeje

i have onkyo tx nr-646 and the plugin dont activate the avr and dont deactivate avr.

Thanks

Onkyo remote app is working

**Comment by uronito** [comment]
I have a modification for models 2015.

Your plugin works perfectly.

Thanks

**Comment by toshibochan** [comment]
I'm not home for a month, when I back I will test! Thanks for update!

**Comment by uronito** [comment]
In the last version if onkyo is unplugged from plug plugin crash.

Before launch onkyo.Connect should check httprequest.

Thanks

**Comment by gw-wiscon** [comment]
I know. 
The code needs a change, I need to build a PowerON / PowerOFF fucntion that checks the connectivity and connects if no connection exist, contains a try/catch block to catch errors, etc.
Requires just some time.

**Comment by uronito** [comment]
0.1.31 don't crash if onkyo is unplugged but if onkyo is unplugged and turn on from plugin, homebridge change state to on and plugin log says Setting power On......... and is waiting

Thanks

**Comment by gw-wiscon** [comment]
Yeah, just solved the crash.
Reconnect is another matter.
The module I found is not very helpful.

Most likely need to switch to another one.
Will see tomorrow.

**Comment by uronito** [comment]
http://jsfiddle.net/GSSCD/203/

whith this javascript can check if the ip onkyo is online and then connect to onkyo.

But would have implement Img Object in node.

Can you see?

Thanks

**Comment by gw-wiscon** [comment]
Did a major rewrite, can you test?

**Comment by AppleTechy** [comment]
Yep.

**Comment by uronito** [comment]
Hi gw wiscon,

Plugin crash at load.

[My Onkyo] Getting power state
/usr/local/lib/node_modules/homebridge-onkyo-avr/index.js:87
        this.log( "eventError: %s", error, response);
                                    ^
ReferenceError: error is not defined
    at Object.HttpStatusAccessory.eventError (/usr/local/lib/node_modules/homebr                                                                                                                                                             idge-onkyo-avr/index.js:87:30)
    at EventEmitter.emit (events.js:107:17)
    at command_to_iscp (/usr/local/lib/node_modules/homebridge-onkyo-avr/node_mo                                                                                                                                                             dules/eiscp/eiscp.js:185:18)
    at EventEmitter.self.command (/usr/local/lib/node_modules/homebridge-onkyo-a                                                                                                                                                             vr/node_modules/eiscp/eiscp.js:445:14)
    at Object.HttpStatusAccessory.getPowerState (/usr/local/lib/node_modules/hom                                                                                                                                                             ebridge-onkyo-avr/index.js:163:13)
    at HttpStatusAccessory.pollingtoevent.longpolling (/usr/local/lib/node_modul                                                                                                                                                             es/homebridge-onkyo-avr/index.js:63:9)
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-onkyo-avr/node_mo                                                                                                                                                             dules/polling-to-event/index.js:77:5)
    at Timer.listOnTimeout (timers.js:110:15)
root@DiskStation:/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/e                                                                                                                                                             iscp# cd ..
root@DiskStation:/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules#

**Comment by uronito** [comment]
Excuse plugin load well, i had write tx646 in config.json

The problem is when turn on onkyo or turn off,  the plugin stops responding for about 30 seconds

if onkyo is unplugged, plugin crash

Thanks

**Comment by gw-wiscon** [comment]
which version did you load?

This looks like a problem, I already solved.

**Comment by uronito** [comment]
wowwwww!!!!!!

The plugin works perfect, but if the receiver is unplugged and send some command, the plugin stops responding (polling state) for 10 seconds or so

missing only if the receiver is unplugged and send the on command , the state returned Homebridge off , as you have achieved in the plug- philips

Thanksssss!!!!!!

**Comment by AppleTechy** [comment]
For some reason when I go to run it I get(My receiver is powered on an running when I started homebridge), 
[FR Onkyo AVR] Initializing OnkyoAVR accessory...
[FR Onkyo AVR] start long poller..
[FR Onkyo AVR] Getting power state
/usr/local/lib/node_modules/homebridge-onkyo-avr/index.js:87
    this.log( "eventError: %s", error, response);
                                ^

ReferenceError: error is not defined
    at Object.HttpStatusAccessory.eventError (/usr/local/lib/node_modules/homebridge-onkyo-avr/index.js:87:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at command_to_iscp (/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/eiscp.js:185:18)
    at EventEmitter.self.command (/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/eiscp.js:445:14)
    at Object.HttpStatusAccessory.getPowerState (/usr/local/lib/node_modules/homebridge-onkyo-avr/index.js:179:13)
    at HttpStatusAccessory.pollingtoevent.longpolling (/usr/local/lib/node_modules/homebridge-onkyo-avr/index.js:63:9)
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/polling-to-event/index.js:77:5)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by AppleTechy** [comment]
In my config I have this set 
{
    "accessory": "OnkyoAVR",
    "name": "FR Onkyo AVR",
    "ip_address": "192.168.1.40",
    "model" : "HT-RC270",
    "poll_status_interval": "900"
}
Did I do something wrong in my config?

**Comment by uronito** [comment]
hi,

the model must be: "TX-NR609"

you must be write "TX-NR609" in model.

**Comment by AppleTechy** [comment]
@uronito Ok. Why is that an included field in the config then?

**Comment by uronito** [comment]
For test purposes,

depend on the model eiscp.js must be modificated.

Can you test it and say me if works?

Thanks

**Comment by AppleTechy** [comment]
@uronito Test the plugin or modify the eisc.js to change the model?

**Comment by uronito** [comment]
test the plugin with modification of config.json-----> "model" : "TX-NR609"

Thanks

**Comment by AppleTechy** [comment]
@uronito Ok. I changed it in the config and it seems to be running smoothly.. Will there be an audio up/down function added?

**Comment by AppleTechy** [comment]
No issues but this is what is appearing in terminal as I have it polling every 60 sec
[FR Onkyo AVR] Getting power state
[FR Onkyo AVR] Event - Power message received:  true
[FR Onkyo AVR] setPowerState -- context: statuspoll, ignore, state: true
[FR Onkyo AVR] PWR Q: false - null -- current state: true
[Harmony Hub] Error refreshing status: TypeError: Cannot read property 'result' of undefined
[FR Onkyo AVR] Getting power state
[FR Onkyo AVR] Event - Power message received:  true
[FR Onkyo AVR] setPowerState -- context: statuspoll, ignore, state: true
[FR Onkyo AVR] PWR Q: false - null -- current state: true
[Harmony Hub] Error refreshing status: TypeError: Cannot read property 'result' of undefined
[FR Onkyo AVR] Getting power state
[FR Onkyo AVR] Event - Power message received:  true
[FR Onkyo AVR] setPowerState -- context: statuspoll, ignore, state: true
[FR Onkyo AVR] PWR Q: false - null -- current state: true

**Comment by uronito** [comment]
is correct.

in config.json 

change "poll_status_interval": "900"

**Comment by AppleTechy** [comment]
@uronito Does it make a difference for your purposes on how often I have it polling? And do you have an ETA when a volume function will be added?

**Comment by uronito** [comment]
No diferences.

In models 2015 the data packet is diferent.

I don't know anything about volume function.

Thanks

**Comment by AppleTechy** [comment]
@uronito I think you would have to set it as a dimming light switch. Not sure how the sonos plugin does it though

**Comment by uronito** [comment]
I think that the sonos plugin work as a switch.

**Comment by uronito** [comment]
Homekit don't have capabilities for a work as a complete remote controller

**Comment by AppleTechy** [comment]
@uronito I know but you could say turn on Onkyo volume up. This then would turn up the audio by 1 or what ever the user has set it in the config. Then this Light auto turns off in 2 sec. Then you can say the command again which then sends the command. You could even build in an accessory for Volume up 1 2 or 5 volume bumps

**Comment by uronito** [comment]
would can make it but i don't see any utility.

**Comment by AppleTechy** [comment]
@uronito For me the utility in it is I have a relative who has a hard time seeing and the ability for them to adjust the tv volume would by voice command would be helpful as they can't see the remote and therefore can't change the volume on the tv.

**Comment by uronito** [comment]
Is a good utility but i don't have a lot of time.

you can do it so.

It's not very difficult.

**Comment by AppleTechy** [comment]
@uronito Can you point me in the right path to where I would add that? I don't have a ton of coding experience but willing to give it a try. I would make it a preset accessory and can I tell it to auto turn off after x amount of seconds?

**Comment by AppleTechy** [comment]
@uronito When I tried to use Charles Proxy to intercept any data between the mobile app and the receiver all I got was the initial connection?

**Comment by uronito** [comment]
hi gw wiscon,

if onkyo is unplugged and run homebridge, homebridge crash

Homebridge is running on port 51826.
[My Philips TV] Polling
[My Philips TV] Getting power state
[My Onkyo] Getting power state
/usr/local/lib/node_modules/homebridge-onkyo-avr/index.js:87
        this.log( "eventError: %s", error, response);
                                    ^
ReferenceError: error is not defined
    at Object.HttpStatusAccessory.eventError (/usr/local/lib/node_modules/homebridge-onkyo-avr/index.js:87:30)
    at EventEmitter.emit (events.js:107:17)
    at /usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/eiscp.js:413:10
    at /usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/node_modules/async/lib/async.js:987:13
    at Immediate.q.process [as _onImmediate](/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/node_modules/async/lib/async.js:953:21)
    at processImmediate [as _immediateCallback](timers.js:358:17)
root@DiskStation:/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp#

In model tx-nr646 (models 2015) , have to change eiscp.js : 

iscp_msg = new Buffer(data + '\x1A\x0d\x0a');

the rest works perfect

Regards

**Comment by gw-wiscon** [comment]
This looks like an error in the log statement.
Let me check the code.

**Comment by gw-wiscon** [comment]
The line should be:
this.log( "eventError: %s", response);

Can you try?

**Comment by uronito** [comment]
of course

giveme a minute

**Comment by gw-wiscon** [comment]
By the way, you have a Windows PC, an Onkyo AVR and a Philips TV?

**Comment by uronito** [comment]
wow, runs perfect now. The only thing if onkyo is unplugged and turn on in the plugin, don't get false state of power, it shown power on in homebridge.

Yes i have onkyo winpc and philipstv

Your 3 plugin :)

Regards

**Comment by uronito** [comment]
By the way, winpc runs perfect!!!!!!!

**Comment by gw-wiscon** [comment]
Yeah, that is something, I need to find a solution for.
Somewhere this week, I guess.

Good that WinPC works.

Just curious, from your time zone, I assume you live in the USA, correct?
Is the Philips TV an American model?

**Comment by uronito** [comment]
No , I'm Spanish.

My philips is european model.

**Comment by gw-wiscon** [comment]
Funny, and you have a raspberry pi and an iphone.
The similarity in tech choices amazes me.

**Comment by uronito** [comment]
jejeje, 
is much chance

raspberry no, i have a synology diskstation with debian and homebridge.

Iphone yes, 5s.

**Comment by AppleTechy** [comment]
@uronito I started looking into the audio and asked @pdlove some questions
about it and he actually is helping write the audio implication as the
files that the plugin is based on already has the volume function built in
and the homebirdge plugin hadn't been taking advantage of it. We are
currently testing a version that does that but we had run into problems
with our previous betas and are working on a newer version that will work
bettter

**Comment by uronito** [comment]
@AppleTechy is fantastic, i'm sure that you will do it

**Comment by AppleTechy** [comment]
I just update to the newest version and when trying to run homebridge I recieve this error. `.nvm/versions/node/v4.2.4/lib/node_modules/homebridge-onkyo-avr/index.js:66
                done(error, response, setAttempt);
                                      ^

ReferenceError: setAttempt is not defined
    at /Users/applegeek/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge-onkyo-avr/index.js:66:27
    at Object.HttpStatusAccessory.getPowerState (/Users/Applegeek/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge-onkyo-avr/index.js:184:2)
    at HttpStatusAccessory.pollingtoevent.longpolling (/Users/applegeek/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge-onkyo-avr/index.js:64:9)
    at null._onTimeout (/Users/applegeek/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge-onkyo-avr/node_modules/polling-to-event/index.js:77:5)
    at Timer.listOnTimeout (timers.js:92:15)
`
My config looks like {
            "accessory": "OnkyoAVR",
            "name": "FR Onkyo Reciever",
            "ip_address": "192.168.1.52",
            "model": "TX-NR609",
            "poll_status_interval": "60"
        }

**Comment by gw-wiscon** [comment]
Sorry, forgot to test the poll mode.
Corrected the bug.
Let me know if it works.
Thanks!!

**Comment by AppleTechy** [comment]
@gw-wiscon It seems to be working now. Thanks for the fix. :)

**Comment by gw-wiscon** [comment]
I am happy you are set.
