### ISSUE TITLE
If onkyo is unplugged, plugin crash at load homebridge

### ISSUE THREAD

**Issue by uronito** [gw-wiscon/homebridge-onkyo-avr#4]
hi gw-wiscon, i have went out a week, i come back jeje,

If Onkyo is unplugged, plugin crash at load homebirdge.

Homebridge is running on port 51826.
[Ordenador Portatil] start polling..
[Ordenador Portatil] getPowerState - actual mode
[My Philips TV] start polling..
[My Philips TV] getPowerState - actual mode
[My Onkyo] start polling..
[My Onkyo] event - status poller - new state:  false
[My Onkyo] setPowerState - polling mode, ignore, state: false
[My Onkyo] getPowerState - actual mode, return state:  false
[Ordenador Salon] start polling..
[Ordenador Salon] getPowerState - actual mode
[My Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"
[My Onkyo] getPowerState - PWR QRY: ERROR - current state: false
/usr/local/lib/node_modules/homebridge-onkyo-avr/index.js:191
                        that.switchService.getCharacteristic(Characteristic.On).setValue(powerOn, n
                                                                                         ^
ReferenceError: powerOn is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-onkyo-avr/index.js:191:70)
    at Object.callback (/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/eiscp.js:429:17)
    at /usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/node_modules/async/lib/async.js:906:35
    at _arrayEach (/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/node_modules/async/lib/async.js:85:13)
    at /usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/node_modules/async/lib/async.js:898:17
    at /usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/eiscp.js:414:5
    at /usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/node_modules/async/lib/async.js:987:13
    at Immediate.q.process [as _onImmediate](/usr/local/lib/node_modules/homebridge-onkyo-avr/node_modules/eiscp/node_modules/async/lib/async.js:953:21)
    at processImmediate [as _immediateCallback](timers.js:358:17)
root@DiskStation:/# service avahi-daemon start

Regards

**Comment by gw-wiscon** [comment]
Hi Uronito,
I believe I found and corrected the problem.
Can you check?

**Comment by uronito** [comment]
give me a minute please

**Comment by uronito** [comment]
Perfect, the plugin don't crash if onkyo is unplugged.

:)

**Comment by gw-wiscon** [comment]
Happy, that this one is solved.
Will close this issue.
